services:
  mongo:
    image: mongo:7
    container_name: mearn-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: mearn_db
    ports:
      - "4301:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    networks:
      - mearn-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mearn-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_URL=${MONGO_URL}
    depends_on:
      - mongo
    ports:
      - "${BACKEND_PORT}:${BACKEND_INTERNAL_PORT}"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mearn-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mearn-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - VITE_API_BASE=/api
    ports:
      - "3201:3201"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mearn-net

networks:
  mearn-net:
    driver: bridge

volumes:
  mongo_data:
